export const users = [
	{ id: 1, name: 'tony', email: 'tony', surname: 'stark', age: 45, cool: true },
	{
		id: 2,
		name: 'steve',
		email: 'steve',
		surname: 'strange',
		age: 40,
		cool: true,
	},
	{
		id: 3,
		name: 'bruce',
		email: 'bruce',
		surname: 'banner',
		age: 35,
		cool: false,
	},
	{
		id: 4,
		name: 'steve',
		email: 'steve',
		surname: 'rogers',
		age: 73,
		cool: false,
	},
	{ id: 5, name: 'sia', email: 'sia', surname: 'yung', age: 33, cool: true },
	{
		id: 6,
		name: 'mystic',
		email: 'mystic',
		surname: 'man',
		age: 30,
		cool: false,
	},
];

export const companies = [
	{
		id: 1,
		company: 'InoRain',
		category: 'OTT',
		start: 2017,
		end: 2099,
		isActive: true,
	},
	{
		id: 2,
		company: 'Synopsys',
		category: 'Hardware',
		start: 2004,
		end: 2020,
		isActive: true,
	},
	{
		id: 3,
		company: 'Cisco',
		category: 'Hardware',
		start: 2011,
		end: 2019,
		isActive: true,
	},
	{
		id: 4,
		company: 'Netflix',
		category: 'Media',
		start: 2014,
		end: 2021,
		isActive: false,
	},
	{
		id: 5,
		company: 'Marvel',
		category: 'Comics',
		start: 2008,
		end: 2019,
		isActive: false,
	},
];
